version: '3'
services:
  api:
    build: ./api
    env_file:
      - ./api/dev.env
    volumes:
      - ./api:/api
    ports:
      - 5000:5000
    container_name: musictimeline_api
  kafka:
    build: ./kafka
    env_file:
      - ./kafka/dev.env
    volumes:
      - ./kafka:/kafka
    command:
      - python
      - "consumer.py"
    container_name: musictimeline_kafka
  cronjob:
    build: ./cronjob
    env_file:
      - ./cronjob/dev.env
    volumes:
      - ./kafka:/kafka
    container_name: musictimeline_cronjob